language: ruby
sudo: false

before_install:
- openssl aes-256-cbc -K $encrypted_4e2dc614325b_key -iv $encrypted_4e2dc614325b_iv -in tra.enc -out tra -d
- chmod 600 tra
- node -v
- npm install

rvm:
- 2.2

cache:
  bundler: true
  directories:
    - node_modules

addons:
  ssh_known_hosts: git.coding.net

script:
  - bundle exec rake build

after_script:
  - cd __public
  - git init
  - git config user.name "travis-ci"
  - git config user.email "support@travis-ci.com"
  - git add .
  - git commit -m "update at `date`"
  - eval `ssh-agent -s`
  - ssh-add tra
  - git push --force "https://git.coding.net/dgeibi/note.git" master:coding-pages

branches:
  only:
    - master
