# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dgeibi's blog
email: png.inside@gmail.com
description: dgeibi's blog
baseurl: ""
url: "https://dgeibi.xyz"
lang: cmn-hans
author: dgeibi
twitter_username: dgeibi
github_username:  dgeibi
disqus_shortname: dgeibi
duoshuo_id: dgeibi
permalink: '/:year/:month/:day/:title/'
paginate: 10
timezone: Asia/Shanghai

collections:
  my_categories:
    output: true
    permalink: '/category/:name/'

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
          path: ""
          type: "my_categories"
        values:
          layout: "blog_by_category"
    -
        scope:
            path: "notes"
        values:
            layout: "note"
            toc: true
    -
        scope:
            path: "notes/css"
        values:
            note: "css"
    -
        scope:
            path: "notes/javascript"
        values:
            note: "javascript"
    -
        scope:
            path: "notes/html"
        values:
            note: "html"
    -
        scope:
            path: "notes/bash"
        values:
            note: "bash"
    -
        scope:
            path: "notes/system"
        values:
            note: "system"
    -
        scope:
            path: "notes/tools"
        values:
            note: "tools"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    auto_ids: false

exclude: ["Gemfile", "Gemfile.lock", "Rakefile"]
