# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dgeibi's blog
email: png.inside@gmail.com
description:
baseurl: ""
url: "https://dgeibi.github.io"
lang: cmn-hans
author: dgeibi
twitter_username: dgeibi
github_username:  dgeibi
disqus_shortname: dgeibi
duoshuo_id: dgeibilog
permalink: '/:year/:month/:day/:title/'
paginate: 10

collections:
  my_categories:
    output: true
    permalink: '/category/:name/'

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
          path: ""
          type: "my_categories"
        values:
          layout: "blog_by_category"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    auto_ids: false

exclude: ["Gemfile", "Gemfile.lock", "Rakefile"]
