title: dgeibi's blog
email: png.inside@gmail.com
description: dgeibi's blog
baseurl: ""
url: "https://dgeibi.xyz"
lang: cmn-hans
author: dgeibi
twitter_username: dgeibi
github_username:  dgeibi
disqus_shortname: dgeibi
duoshuo_id: dgeibi
permalink: '/:year/:month/:day/:title/'
paginate: 10
timezone: Asia/Shanghai
google-analytics: UA-86886156-1

highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    auto_ids: false

jekyll-archives:
  enabled:
    - year
    - month
    - categories
  layouts:
    year: year-archive
    month: month-archive
    category: category-archive
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    category: '/archives/category/:name/'

exclude: ["vendor", "Gemfile", "Gemfile.lock", "Rakefile"]

gems:
  - jekyll-assets
  - jekyll-archives

assets:
  compress:
      css: true
      js: true
  autowrite: true
  sources:
    - _assets/css
    - _assets/js

  prefix: "/assets"

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            comment: true
    -
        scope:
            path: "notes"
        values:
            layout: "note"
            toc: true
            comment: true
    -
        scope:
            path: "notes/css"
        values:
            note: "css"
    -
        scope:
            path: "notes/javascript"
        values:
            note: "javascript"
    -
        scope:
            path: "notes/html"
        values:
            note: "html"
    -
        scope:
            path: "notes/bash"
        values:
            note: "bash"
    -
        scope:
            path: "notes/system"
        values:
            note: "system"
    -
        scope:
            path: "notes/tools"
        values:
            note: "tools"
