title: dgeibi's notebook
email: png.inside@gmail.com
description: dgeibi's notebook
baseurl: ''
url: https://note.dgeibi.xyz
lang: cmn-hans
author: dgeibi
timezone: Asia/Shanghai
highlighter: rouge
markdown: kramdown
kramdown: {input: GFM, auto_ids: false}
exclude: [vendor, Gemfile, Gemfile.lock, Rakefile, yarn.lock, package.json, README.md,
  getConfig.js]
collections:
  bash: {output: true, permalink: '/:collection/:path/'}
  css: {output: true, permalink: '/:collection/:path/'}
  ecmascript: {output: true, permalink: '/:collection/:path/'}
  html: {output: true, permalink: '/:collection/:path/'}
  network: {output: true, permalink: '/:collection/:path/'}
  system: {output: true, permalink: '/:collection/:path/'}
  tools: {output: true, permalink: '/:collection/:path/'}
  webapi: {output: true, permalink: '/:collection/:path/'}
defaults:
- scope: {path: '', type: bash}
  values: {layout: note, toc: true}
- scope: {path: '', type: css}
  values: {layout: note, toc: true}
- scope: {path: '', type: ecmascript}
  values: {layout: note, toc: true}
- scope: {path: '', type: html}
  values: {layout: note, toc: true}
- scope: {path: '', type: network}
  values: {layout: note, toc: true}
- scope: {path: '', type: system}
  values: {layout: note, toc: true}
- scope: {path: '', type: tools}
  values: {layout: note, toc: true}
- scope: {path: '', type: webapi}
  values: {layout: note, toc: true}
