# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: dgeibi's blog
email: png.inside@gmail.com
description: just another Jekyll blog
baseurl: ""
url: "https://dgeibi.github.io"
twitter_username: dgeibi
github_username:  dgeibi

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 parse_block_html: false
enforce_ssl: dgeibi.github.io
