title: dgeibi's notebook
email: png.inside@gmail.com
description: dgeibi's notebook
baseurl: ""
url: "https://note.dgeibi.xyz"
lang: cmn-hans
author: dgeibi
timezone: Asia/Shanghai

highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    auto_ids: false

collections:
    html:
        output: true
        permalink: /:collection/:path/
    ecmascript:
        output: true
        permalink: /:collection/:path/
    css:
        output: true
        permalink: /:collection/:path/
    system:
        output: true
        permalink: /:collection/:path/
    bash:
        output: true
        permalink: /:collection/:path/
    webapi:
        output: true
        permalink: /:collection/:path/
    tools:
        output: true
        permalink: /:collection/:path/

exclude: ["vendor", "Gemfile", "Gemfile.lock", "Rakefile"]

defaults:
    -
        scope:
            path: ""
            type: "html"
        values:
            layout: "note"
            toc: true
    -
        scope:
            path: ""
            type: "ecmascript"
        values:
            layout: "note"
            toc: true
    -
        scope:
            path: ""
            type: "css"
        values:
            layout: "note"
            toc: true
    -
        scope:
            path: ""
            type: "bash"
        values:
            layout: "note"
            toc: true
    -
        scope:
            path: ""
            type: "system"
        values:
            layout: "note"
            toc: true
    -
        scope:
            path: ""
            type: "tools"
        values:
            layout: "note"
            toc: true
    -
        scope:
            path: ""
            type: "webapi"
        values:
            layout: "note"
            toc: true
